---
development:
  cloud_name: yamaokaya
  api_key: '346563546529686'
  api_secret: Is42MmLkI3Y00H5CIiKKh-pQtCw
  enhance_image_tag: true
  static_image_support: true
  cdn_subdomain: true
production:
  cloud_name: yamaokaya
  api_key: '346563546529686'
  api_secret: Is42MmLkI3Y00H5CIiKKh-pQtCw
  enhance_image_tag: true
  static_image_support: true
  cdn_subdomain: true
test:
  cloud_name: yamaokaya
  api_key: '346563546529686'
  api_secret: Is42MmLkI3Y00H5CIiKKh-pQtCw
  enhance_image_tag: true
  static_image_support: true
